# It is applied to define a parameteric relative stable orbit around an orbital station in circular orbit around a massive body.


float64 rho_r    #Aplitude of the relative orbit in the radial direction
float64 rho_s    #shift of the orbot in the along-track direction (it is not an aplitude per se, but it is a shift of the orbot with respect to the center)
float64 rho_w    #amplitude of the orbit in the cross-track direction                                                                                       
float64 alpha_r  #phase of the orbot in the orbotal plane
float64 alpha_w  #phase of the orbit in the cross-track direction 
